Develop
DigitalGovernmentLabs/dgl-info pull request #11
Opened 2020-07-24 09:31 UTC by maccostar

## Types of changes

What kind of change does this PR introduce? (check at least one)

- [ ] Breaking change
- [ ] Bugfix
- [x] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

## Description

Issue Number: N/A

### ▼feat: Add a page and components to add, update and delete links.
linkを追加・更新・削除するページとその従属するコンポーネントを追加しました。

#### changed files
- pages/mynum/links.vue
- components/pages/mynum/links/AddLinkDialog.vue
- components/pages/mynum/links/UpdateLinkDialog.vue

### ▼feat: add request methods for fetching, adding, updating and removing lists and links
以下のリストとリンクを操作するためのリクエストメソッドを追加しました。
- リンクリストおよびリンクの全件取得
- リンクリストの追加
- リンクの追加
- リンクの更新
- リンクの削除

#### changed files
- リンクリストおよびリンクの全件取得/リンクリストの追加
  - server/api/linkLists/index.ts
  - server/api/linkLists/@controller.ts
- リンクの追加
  - server/api/links/_linkListId@number/index.ts
  - server/api/links/_linkListId@number/@controller.ts
- リンクの更新/リンクの削除
  - server/api/links/_linkId@number/index.ts
  - server/api/links/_linkId@number/@controller.ts
- メソッドの記述なし
  - server/api/links/index.ts
  - server/api/links/@controller.ts

### ▼feat: add domain services between the above-mentioned request methods and the DB
前述のリクエストメソッドとDB間を繋ぐドメインサービスを追加しました。

#### changed files
  - server/service/linkLists.ts
  - server/service/links.ts

### ▼feat: defined types and entities to be stored in the DB
以下のデータの型定義とDBに格納するためのエンティティの定義を行いました。
(I defined the following data types and entities to be stored in the DB.)
- LinkList
- Link

#### changed files 
- server/types/index.ts
- server/entity/Link.ts
- server/entity/LinkList.ts
- server/linkLists.json
- server/migration/1594447796773-Task.ts  

### ▼chore:change setting

- vueutifyの追加・適用
- eslintルールの追加
- stylelint-moduleの適用
- frourioのバージョン更新

#### changed files

- .eslintrc.js
- nuxt.config.ts
- package.json
- package-lock.json
- layouts/default.vue
- tsconfig.json
- yarn.lock
- server/yarn.lock 
server/ormconfig.ts

2020-07-24 13:01 UTC, solufa commented on server/service/links.ts
> +// eslint-disable-next-line complexity
消す

2020-07-24 13:01 UTC, solufa commented on server/service/links.ts
> +  await linkRepository().save(link)
const link = await linkRepository().findOne({ linkId })
  if (!link) return

  const { name, url, description } = {
    ...link,
    ...partialLink
  }

  await linkRepository().save({ name, url, description })

2020-07-25 05:09 UTC, maccostar commented on components/pages/mynum/links/AddLinkDialog.vue
> +<script lang="ts">
ご指摘ありがとうございます。修正しました。

2020-07-25 05:16 UTC, maccostar commented on components/pages/mynum/links/AddLinkDialog.vue
> +          @click=";(dialog = false), addListTitle()"
addListTitleに下記を追加し、38行目からは削除しました。
`this.dialog=false`

2020-08-01 11:13 UTC, maccostar commented on pages/mynum/links.vue
> +          <h2>
ご指摘ありがとうございます。修正しました。

2020-08-01 11:14 UTC, maccostar commented on pages/mynum/links.vue
> +                <v-list-item-subtitle>
ご指摘ありがとうございます。修正しました。

2020-08-01 11:15 UTC, maccostar commented on server/service/linkLists.ts
> +  linkListRepository().findOneOrFail({ listId })
ご指摘ありがとうございます。修正しました。

2020-08-01 13:22 UTC, maccostar commented on pages/mynum/links.vue
> +                    >{{ link.url }}</a
修正しました。

2020-08-01 13:27 UTC, maccostar commented on server/service/linkLists.ts
> +  const newList = {
以下に変更しました。
`  const newList: Pick<LinkList, 'listOrder' | 'listTitle'> = {
    listOrder: newOrder,
    listTitle
  }
`

2020-08-01 13:29 UTC, maccostar commented on server/service/links.ts
> +  await linkRepository().save(newLink)
以下に変更しました。
```
  const newLink: Omit<Link, 'linkId'> = {
    linkOrder: newOrder,
    url: link.url,
    name: link.name,
    description: link.description,
    linkList
  }
```

2020-08-01 13:37 UTC, maccostar commented on server/service/links.ts
> +// eslint-disable-next-line complexity
削除しました。

2020-08-01 13:38 UTC, maccostar commented on server/service/links.ts
> +  await linkRepository().save(link)
以下に変更しました。
```
  const updatedLink = await linkRepository().findOne({ linkId: link.linkId })
  if (!updatedLink) return

  const { name, url, description } = {
    ...updateLink,
    ...link
  }

  await linkRepository().save({
    linkId: updatedLink.linkId,
    linkOrder: updatedLink.linkOrder,
    name,
    url,
    description
  })
```

2020-08-01 14:28 UTC, maccostar commented on server/api/linkLists/@controller.ts
> +  }
statusを204に変更したため、以下の通り変更します。
```
  post: async ({ body }) => {
    await createLinkList(body.listTitle)
    return { status: 204 }
  }
```

2020-08-01 14:29 UTC, maccostar commented on server/api/linkLists/index.ts
> +    resBody: LinkList[]
statusを204にして、links.vueで再度getし直すように変更しました。

2020-08-01 14:30 UTC, maccostar commented on server/api/links/_linkListId@number/@controller.ts
> +    return { status: 201 }
204に変更しました。

2020-08-01 14:30 UTC, maccostar commented on server/entity/Link.ts
> +    (type) => LinkList,
修正しました。

2020-08-01 14:31 UTC, maccostar commented on server/entity/LinkList.ts
> +  /* eslint-disable */
削除しました。

2020-08-01 14:33 UTC, maccostar commented on server/ormconfig.ts
> +dotenv.config({ path: '' })
修正しました。

2020-08-02 08:07 UTC, maccostar commented on server/service/linkLists.ts
> +      ? Math.max(...linkLists.map((linkList: LinkList) => linkList.listOrder)) +
以下の通り、listOrderの最大数をtypeORMで取得するように変更しました。
```
  type MaxObject = { maxOrder?: LinkList['listOrder'] }

  const maxObject: MaxObject = await linkListRepository()
    .createQueryBuilder('linklist')
    .select('MAX(linklist.listOrder)', 'maxOrder')
    .getRawOne()

  const newOrder = maxObject.maxOrder ? maxObject.maxOrder + 1 : 0
```

2020-08-02 09:08 UTC, maccostar commented on server/service/linkLists.ts
> +    .getMany()
SQLで取得する際にORDER BYを行うように変更しました。
```
export const findAllLists = () =>
  linkListRepository()
    .createQueryBuilder('linklist')
    .leftJoinAndSelect('linklist.links', 'link')
    .orderBy('linklist.listOrder')
    .addOrderBy('link.linkOrder')
    .getMany()
```

2020-08-02 10:39 UTC, solufa commented on components/pages/mynum/links/UpdateLinkDialog.vue
> +          @click=";(dialog = false), updateLink()"
updateLinkにまとめる

2020-08-02 10:43 UTC, solufa commented on server/service/links.ts
> +  const linkList = await findOneList(listId)
本来DB情報不要なのにsaveのためだけにfindするのを回避したい
JoinColumnとか
https://tech.bitbank.cc/typeorm-entity-guideline/

2020-08-02 10:44 UTC, solufa commented on server/service/links.ts
> +      : 0
最大値はTypeORMで取る

2020-08-02 10:49 UTC, solufa commented on server/service/linkLists.ts
> +  const newOrder = maxObject.maxOrder ? maxObject.maxOrder + 1 : 0
三項演算子の使い方が間違っててmaxOrder がゼロから増えない

2020-08-02 10:51 UTC, solufa commented on server/service/linkLists.ts
> +    listOrder: newOrder,
newOrderを変数に入れるほどの処理ではない
listOrder: (maxObject.maxOrder ?? -1) + 1
orderは1スタートで良い気がする
listOrder: (maxObject.maxOrder ?? 0) + 1

2020-08-02 10:54 UTC, solufa commented on server/types/index.ts
> +}
空行

2020-08-13 23:10 UTC, solufa commented
npm run migration:* コマンドは使える状態？
私が教えた修正が反映されてないような気がする

2020-09-05 11:21 UTC, maccostar commented on components/pages/mynum/links/UpdateLinkDialog.vue
> +          @click=";(dialog = false), updateLink()"
`dialog = false`の記述部分をupdateLinkの中にマージしました。

2020-09-05 11:23 UTC, maccostar commented on server/service/links.ts
> +  const linkList = await findOneList(listId)
ありがとうございます！
たしかに一度DBから取得するの不毛だな...と思っていたので、JoinColumn勉強になりました。

修正対応していますので、ご確認ください。

2020-09-05 11:26 UTC, maccostar commented on server/service/links.ts
> +      : 0
`const maxLinkOrder`を追加して、クエリビルダでmax値を取得するように変更しました。

本当はSQLの中で、NVL関数をセットしたかったのですが、
DB毎で仕様がバラバラのようでしたので、20行目にmaxLinkOrderが`{ max: null }`だった場合の処理を記述しています。

2020-09-05 11:27 UTC, maccostar commented on server/service/linkLists.ts
> +  const newOrder = maxObject.maxOrder ? maxObject.maxOrder + 1 : 0
Line25-28への指摘と併せて対応しました。

2020-09-05 11:27 UTC, maccostar commented on server/service/linkLists.ts
> +    listOrder: newOrder,
ご提案の内容で修正しました。

2020-09-05 11:27 UTC, maccostar commented on server/types/index.ts
> +}
空行を追加しました。

2020-09-05 11:41 UTC, maccostar commented
@solufa 
いただいていたご指摘を修正対応しました。お手数ですがご確認をお願いします。

2020-09-05 21:28 UTC, solufa requested changes
あと少し修正

2020-09-05 21:28 UTC, solufa commented on components/pages/mynum/links/UpdateLinkDialog.vue
> +<script lang="ts">
空行欲しい

2020-09-05 21:28 UTC, solufa commented on server/service/links.ts
> +// import { findOneList } from './linkLists'
消す

2020-09-05 21:28 UTC, solufa commented on server/service/linkLists.ts
> +export const findOneList = (listId: LinkList['listId']) =>
不要では

2020-09-05 21:28 UTC, solufa commented on server/service/links.ts
> +    linkOrder: maxLinkOrder.max === 'number' ? maxLinkOrder.max + 1 : 1,
maxLinkOrder.max を文字列型と比較しているけどそのあとは計算に使ってて数値型に見える

比較か計算どっちかの処理が間違ってる

2020-09-05 21:28 UTC, solufa commented on server/service/links.ts
> +  if (removedLink) await linkRepository().remove(removedLink)
deleteを使うと1行で消せそう
ついでに名前をdeleteLinkに変える
https://github.com/typeorm/typeorm/blob/master/docs/repository-api.md

2020-09-12 12:06 UTC, maccostar commented on server/service/links.ts
> +// import { findOneList } from './linkLists'
削除しました。

2020-09-12 12:07 UTC, maccostar commented on server/service/linkLists.ts
> +export const findOneList = (listId: LinkList['listId']) =>
すみません。確かに前回の改修で未使用となっていました。
削除しました。

2020-09-12 12:07 UTC, maccostar commented on components/pages/mynum/links/UpdateLinkDialog.vue
> +<script lang="ts">
追加しました。

2020-09-12 12:39 UTC, maccostar commented on server/service/links.ts
> +    linkOrder: maxLinkOrder.max === 'number' ? maxLinkOrder.max + 1 : 1,
typeofで比較しようと思っていましたが、記述が漏れていました。
修正しました。

2020-09-12 12:39 UTC, maccostar commented on server/service/links.ts
> +  if (removedLink) await linkRepository().remove(removedLink)
ありがとうございます。deleteメソッドあるんですね。勉強になりました！

2020-09-12 12:49 UTC, merged